SportsStore/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportsStore.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SportsStore/Controllers/ShoppingCardController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using SportsStore.ViewModel;
using System;
using System.Collections.Generic;
using System.Composition.Convention;
using System.Linq;
using System.Threading.Tasks;

namespace SportsStore.Controllers
{
    public class ShoppingCardController : Controller
    {
        private readonly ISportsGoodsRepository _sportsGoodsRepository;
        private readonly ShoppingCard _shoppingCard;

        public ShoppingCardController(ISportsGoodsRepository sportsGoodsRepository, ShoppingCard shoppingCard)
        {
            _sportsGoodsRepository = sportsGoodsRepository;
            _shoppingCard = shoppingCard;
        }

        public ViewResult Index()
        {
            _shoppingCard.ShoppingCardItems = _shoppingCard.GetShoppingCardItems();

            var shoppingcardVM = new ShoppingCardViewModel
            {
                ShoppingCard = _shoppingCard,
                ShoppingCardTotal = _shoppingCard.GetTotal()
            };
            return View(shoppingcardVM);
        }

        public RedirectToActionResult AddToShoppingCard(int goodId)
        {
            var selecteditem = _sportsGoodsRepository.GetAllGoods.FirstOrDefault(c=>c.GoodsId==goodId);

            if (selecteditem != null)
            {
                _shoppingCard.AddToCard(selecteditem, 1);
            }
            return RedirectToAction("List", "SportsGood");
        }

        public RedirectToActionResult RemoveFromShoppingCard(int goodId)
        {
            var selecteditem = _sportsGoodsRepository.GetAllGoods.FirstOrDefault(c => c.GoodsId == goodId);

            if (selecteditem != null)
            {
                _shoppingCard.RemoveFromCard(selecteditem);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult ClearCart()
        {
            _shoppingCard.ClearCard();
            return RedirectToAction("Index");
        }
    }
}

SportsStore/Controllers/SportsGoodController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using SportsStore.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportsStore.Controllers
{
    public class SportsGoodController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly ISportsGoodsRepository _sportsGoodsRepository;

        public SportsGoodController(ICategoryRepository categoryRepository, ISportsGoodsRepository sportsGoodsRepository)
        {
            _categoryRepository = categoryRepository;
            _sportsGoodsRepository = sportsGoodsRepository;
        }

        public ViewResult List(string category)
        {
            IEnumerable<SportsGood> sportsGoods;
            string currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                sportsGoods = _sportsGoodsRepository.GetAllGoods.OrderBy(c=>c.GoodsId);
                currentCategory = "All Goods";
            }
            else
            {
                sportsGoods = _sportsGoodsRepository.GetAllGoods.Where(c => c.Category.CategoryName == category);
                currentCategory = _categoryRepository.GetAllCategories
                    .FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }
            var viewModel= new SportsGoodsListViewModel
            {
                SportsGoods = sportsGoods,
                CurrentCategory = currentCategory
            };
            return View(viewModel);
        }

        public IActionResult Details(int id)
        {
            var good = _sportsGoodsRepository.GetGoodById(id);
            if (good == null)
                return NotFound();
            return View(good);
        }
    }
}

SportsStore/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.png" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.png" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.png" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/content/site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button style="height:53px; margin-left:0; background-color:#a593c2" class="openbtn" onclick="openNav()">☰</button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><img style="width:53px; height:53px; margin:0,0,0,0" class="img-responsive" src="~/Images/sportstorelogo.png" /></li>
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <partial name="_LoginPartial" />
                        @await Component.InvokeAsync("ShoppingCardSummary")
                    </ul>
                </div>
            </div>
        </nav>
        <div id="mySidebar" class="sidebar">
            <button href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</button>
            @await Component.InvokeAsync("CategoryMenu")
            <a asp-controller="Contact" asp-action="Index">Contact</a>
        </div>
        <div class="row">
            <div class="col-md-10">
                @RenderBody()
                <div class="footer">
                    <medium>@DateTime.Now.Year &copy; SportStore. Made by H.M.</medium>
                </div>
            </div>
        </div>
        @RenderSection("Scripts", required: false)
    </div>
    <script>
        function openNav() {
            document.getElementById("mySidebar").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
        }

        function closeNav() {
            document.getElementById("mySidebar").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>
    <style>
        body {
            font-family: "Lato", sans-serif;
        }
        .footer {
            position: fixed;
            left: 0;
            bottom: 0;
            padding-bottom: 10px;
            width: 100%;
            background-color: #a593c2;
            color: white;
            text-align: right;
        }
        .sidebar {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
            background-color: #a593c2;
            opacity: 0.9;
        }

            .sidebar a {
                padding: 8px 8px 8px 32px;
                text-decoration: none;
                font-size: 25px;
                color: white;
                display: block;
                transition: 0.3s;
            }

                .sidebar a:hover {
                    color: #f1f1f1;
                }

            .sidebar .closebtn {
                background: transparent;
                border: transparent;
                margin-top: 38px;
                font-size: 30px;
                margin-left: 150px;
            }

        .openbtn {
            font-size: 20px;
            cursor: pointer;
            background-color: #111;
            color: white;
            padding: 10px 15px;
            border: none;
        }

            .openbtn:hover {
                background-color: #444;
            }
    </style>
</body>
</html>

SportsStore/Views/Shared/_sportCard.cshtml
@model SportsGood

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="SportsGood" asp-action="Details"
                   asp-route-id="@Model.GoodsId">@Model.Name</a>
            </h3>
            <p>@Model.Description</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-success" 
                   asp-controller="ShoppingCard" 
                   asp-action="AddToShoppingCard"
                   asp-route-goodId="@Model.GoodsId">Add To Card</a>
            </p>
        </div>
    </div>
</div>